FROM debian:trixie-slim

LABEL maintainer="SaC Development Team <info@sac-home.org>"

RUN apt-get update \
 && apt-get install -y --no-install-recommends \
  linux-base \
  linux-perf \
  build-essential \
  ca-certificates \
  ninja-build \
  cmake \
  curl \
  git \
  numactl \
  python3 \
  xsltproc \
  libsdl3-dev \
  libsdl3-image-dev \
  libsdl3-ttf-dev \
  openmpi-bin \
  libopenmpi-dev \
  libhwloc-dev \
  uuid-runtime \
  uuid-dev \
  bison \
  flex \
  m4 \
 && apt-get clean \
 && apt-get autoclean \
 && apt-get --purge autoremove

ENV SAC2CP_DIR=/sac2c/build/sac2c-release/src/sac2c-release-build
ENV SAC2CD_DIR=/sac2c/build/sac2c-debug/src/sac2c-debug-build
ENV SAC2CP_EXEC=${SAC2CP_DIR}/sac2c_p
ENV SAC2CD_EXEC=${SAC2CD_DIR}/sac2c_d

# Build and install the SaC compiler
RUN git clone --recursive --single-branch https://gitlab.sac-home.org/sac-group/sac2c.git sac2c \
 && cd sac2c \
 && cmake -S cmake/cpack -B build -G Ninja \
 && cmake --build build -j4 \
 && ln -sf $SAC2CP_EXEC /usr/local/bin/sac2c \
 && sac2c -V

# Ensure linker cache is valid
RUN ldconfig

# Build and install the standard library
RUN git clone --recursive --single-branch https://github.com/SacBase/Stdlib.git sac-stdlib \
 && cd sac-stdlib \
 && cmake -S . -B build -G Ninja -DTARGETS="seq;seq_checks;mt_pth" -DBUILD_EXT=ON -DLINKSETSIZE=200 \
 && cmake --build build -j4

# Build and install energy measuring library
RUN git clone --recursive --single-branch https://github.com/SacBase/Energy.git sac-energy \
 && cd sac-energy \
 && cmake -S . -B build -G Ninja -DTARGETS="seq;seq_checks;mt_pth" \
 && cmake --build build

# Copy .sac2crc to home directory
RUN cp -r /root/.sac2crc /home/.sac2crc

WORKDIR /home
